services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: myapp
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:
