CREATE TABLE IF NOT EXISTS T_USER (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  mdp VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS T_ARTICLE (
  id SERIAL PRIMARY KEY,
  auteur_id INTEGER REFERENCES T_USER(id),
  titre TEXT NOT NULL,
  contenu TEXT NOT NULL,
  date_publication TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);